" Use Vim-plug for plugin management
call plug#begin('~/.vim/plugged')

" Plugins.  We must use single quotes

" Per filetype settings
Plug 'editorconfig/editorconfig-vim'

" Rust for vim
Plug 'wting/rust.vim'

" Ultisnips, with vim-snippets (which contains useful snippets)
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" Nerdtree plugin
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }

" Automatically discover and update ctags
Plug 'craigemery/vim-autotag'

" Autocomplete tags automatically
Plug 'ervandew/supertab'

" Fuzzy file buffer etc finder
Plug 'kien/ctrlp.vim'

" Insert mode tab completion
Plug 'ervandew/supertab'

call plug#end()

" Leader options
let mapleader = "\<space>"
let maplocalleader = "-"

set nocompatible " Remove vi compatability

" -- General options --
syntax on                    " Allow syntax highlighting
filetype plugin indent on    " but decent option anyway
"set acd                      " Automatically change to current buffer directory
set backup                   " Make backup files
set backupdir=/tmp           " Write backup files here
set directory=/tmp           " Directory for swap files
set hidden                   " Enables changing buffers without saving
set rnu                      " Show relative numbers
set colorcolumn=81           " Show vertical line at tw=80
set nowrap                   " Don't wrap lines by default
set foldmethod=indent        " Default folding on indenting
set list                     " Show tabs/blankspace
set listchars=tab:>-,trail:- " Show tabs/blankspace
"set mouse=a                  " Use mouse everywhere
set wildmenu                 " Turn on command line completion
set incsearch                " Incremental search
set lazyredraw               " Don't redraw while running macros
set ts=4 sw=4 sts=4          " Default tabs 4 spaces
set expandtab                " Always use spaces instead of tabs

" -- Useful mappings --

" map jk to <esc> in insert and visual mode
inoremap jk <esc>
vnoremap jk <esc>
" Open .vimrc in a split window for easy reference
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
" Source .vimrc (for easy reloading)
nnoremap <leader>sv :source $MYVIMRC<cr>
" close buffer easily and go to previous or new buffer
nnoremap <leader>q :bd<cr>
" make word uppercase and put cursor at the start of the next word
nnoremap <leader>U viwU<esc>w

" disable <esc> mapping to force me to use jk
inoremap <esc> <nop>
vnoremap <esc> <nop>

" command for setting local dir to current file
nnoremap <leader>cd :cd %:p:h<cr>:pwd<cr>

" clear highlighting
nnoremap <leader>h :nohl<cr>

" Toggle NERDtree
nnoremap <leader>d :NERDTreeToggle<cr>

" -- Abbreviations --
" My own signature
iabbrev @@ Written by Nico Gevers <me@gevious.com>

" -- Autocommands --
" Fold the code within the current html tag
augroup FiletypeHtml
 au!
 au FileType html nnoremap <buffer> <localleader>f Vatzf
augroup END

" Highlight cursor line
augroup CursorLine
  au!
  hi CursorLine cterm=bold ctermbg=black ctermfg=white " Cursor line
  au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
  au VimLeave,WinLeave,BufWinLeave * setlocal nocursorline
augroup END

" -- Status line --
set statusline=%.20F              " Filename (max 20 characters)
set statusline+=\ type:%Y\        " Flags [readonly,help,preview]modified
set statusline+=\ [%R%H%W]%M\     " Flags [readonly,help,preview]modified
set statusline+=%=                " Switch to the right side
set statusline+=(%l/%L\ \|%3p%%)  " (current line/total lines|percent)
